swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"
basePath: "/api"
# Paths supported by the server application
paths:
  /user:
    post:
      operationId: "model.create_new_user"
      description: "Creates a new user"
      tags:
        - "Create new user" 
      produces: 
        - "application/json" 
      parameters:
      - name: useridobj
        in: body
        description: Creates a new user
        required: true
        schema:
          type: object
          required:
            - userid
            - password
          properties:
            userid:
              type: string
            password:
              type: string
            user_type:
              type: string
      summary: "creates new user with new pass hash, username and user type "
      # requestBody:
      #   required: true
      #   content:
      #     application/x-www-form-urlencoded:
      #       schema:
      #         type: object
      #         properties:
      #           userid:          # <!--- form field name
      #             type: string
      #           password:    # <!--- form field name
      #             type: string
      #           user_type:    # <!--- form field name
      #             type: string
      #         required:
      #           - name
      #           - email
      responses:
        200:
          description: "Successfully created user"
          schema:
            type: "string"
  /user/validate:
    post:
      operationId: "model.validate_pw"
      tags:
        - "Validate PW" 
      produces: 
        - "application/json" 
      parameters:
      - name: useridobj
        in: body
        description: Validate user
        required: true
        schema:
          type: object
          required:
            - userid
            - password
          properties:
            userid:
              type: string
            password:
              type: string
      summary: "validates username based on password and userid"
      description: "Returns True for valid"
      responses:
        200:
          description: "Successfully validated pw"
          schema:
            type: "string"
  /createquery:
    post:
      operationId: "model.create_new_user_query"
      tags:
        - "Create new user" 
      parameters:
        - name: userid
          in: query
          type: string
          description: "enter the userid so that you can get validate pw with pass hash"
          required: true
        - name: password
          in: query
          type: string
          description: "enter the username so that you can get this users pass hash"
          required: true
        - name: user_type
          in: query
          type: string
          description: "enter the username so that you can get this users pass hash"
          required: true      
      summary: "creates new user with new pass hash, username and user type "
      description: "Returns True for valid"
      responses:
        200:
          description: "Successfully created user"
          schema:
            type: "string"
